Repository wuzuzu/wuzuzu, pull requests merged in 2024-04, with the labels that each got.

#3 Feat/inyeong user auth
  build.gradle
  src/main/java/com/sparta/wuzuzu/domain/common/dto/CommonResponse.java
  src/main/java/com/sparta/wuzuzu/domain/user/controller/MyInformController.java
  src/main/java/com/sparta/wuzuzu/domain/user/controller/UserController.java
  src/main/java/com/sparta/wuzuzu/domain/user/dto/LoginRequest.java
  src/main/java/com/sparta/wuzuzu/domain/user/dto/MyInformReadResponse.java
  src/main/java/com/sparta/wuzuzu/domain/user/dto/MyInformUpdateRequest.java
  src/main/java/com/sparta/wuzuzu/domain/user/dto/SignUpRequest.java
  src/main/java/com/sparta/wuzuzu/domain/user/dto/SignUpResponse.java
  src/main/java/com/sparta/wuzuzu/domain/user/entity/User.java
  src/main/java/com/sparta/wuzuzu/domain/user/entity/UserRole.java
  src/main/java/com/sparta/wuzuzu/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/wuzuzu/domain/user/service/MyInformService.java
  src/main/java/com/sparta/wuzuzu/domain/user/service/UserService.java
  src/main/java/com/sparta/wuzuzu/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/wuzuzu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/wuzuzu/global/jwt/JwtUtil.java
  src/main/java/com/sparta/wuzuzu/global/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/wuzuzu/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/wuzuzu/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/wuzuzu/global/security/UserDetailsServiceImpl.java
Labels: documentation, enhancement

#7 Feat/hsy board
  src/main/java/com/sparta/wuzuzu/WuzuzuApplication.java
  src/main/java/com/sparta/wuzuzu/domain/board_item/controller/BoardItemController.java
  src/main/java/com/sparta/wuzuzu/domain/board_item/dto/BoardItemResponse.java
  src/main/java/com/sparta/wuzuzu/domain/board_item/entity/BoardItem.java
  src/main/java/com/sparta/wuzuzu/domain/board_item/repository/BoardItemRepository.java
  src/main/java/com/sparta/wuzuzu/domain/board_item/service/BoardItemService.java
  src/main/java/com/sparta/wuzuzu/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/wuzuzu/domain/comment/dto/CommentRequest.java
  src/main/java/com/sparta/wuzuzu/domain/comment/dto/CommentResponse.java
  src/main/java/com/sparta/wuzuzu/domain/comment/entity/Comment.java
  src/main/java/com/sparta/wuzuzu/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/wuzuzu/domain/comment/service/CommentSerivce.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/controller/CommunityCategoryController.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/controller/CommunityPostsController.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/controller/LikeController.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/dto/CommunityCategoryRequest.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/dto/CommunityCategoryResponse.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/dto/CommunityPostGet.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/dto/CommunityPostsRequest.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/dto/CommunityPostsResponse.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/dto/PostLikeResponse.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/entity/CommunityCategory.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/entity/CommunityPosts.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/entity/Postlikes.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/repository/CommunityCategoryRepository.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/repository/CommunityPostsRepository.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/repository/PostlikeRepository.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/service/CommunityCategoryService.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/service/CommunityPostsService.java
  src/main/java/com/sparta/wuzuzu/domain/community_posts/service/PostLikeService.java
  src/main/java/com/sparta/wuzuzu/global/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/wuzuzu/global/exception/NotFoundCommunityPostException.java
  src/main/java/com/sparta/wuzuzu/global/exception/ValidateAdminException.java
  src/main/java/com/sparta/wuzuzu/global/exception/ValidateUserException.java
Labels: bug, enhancement

#9 Feat/jjh-s3 S3 이미지 업로드/삭제 요청 & ImageUrl 출력 & Image 테이블화 및 공동화 작업 + 기타 오류 해결
  build.gradle
  src/main/java/com/sparta/wuzuzu/domain/category/service/CategoryService.java
  src/main/java/com/sparta/wuzuzu/domain/common/image/entity/Image.java
  src/main/java/com/sparta/wuzuzu/domain/common/image/repository/ImageRepository.java
  src/main/java/com/sparta/wuzuzu/domain/common/image/service/ImageService.java
  src/main/java/com/sparta/wuzuzu/domain/common/image/service/S3Service.java
  src/main/java/com/sparta/wuzuzu/domain/dibs/controller/DibsController.java
  src/main/java/com/sparta/wuzuzu/domain/order/dto/OrderRequest.java
  src/main/java/com/sparta/wuzuzu/domain/sale_post/controller/SalePostController.java
  src/main/java/com/sparta/wuzuzu/domain/sale_post/dto/SalePostVo.java
  src/main/java/com/sparta/wuzuzu/domain/sale_post/entity/SalePost.java
  src/main/java/com/sparta/wuzuzu/domain/sale_post/repository/query/SalePostQueryRepositoryImpl.java
  src/main/java/com/sparta/wuzuzu/domain/sale_post/service/SalePostService.java
  src/main/java/com/sparta/wuzuzu/global/config/S3Config.java
Labels: bug, documentation, enhancement

#12 Feat/inyeong user auth
  src/main/java/com/sparta/wuzuzu/domain/email/controller/EmailAuthController.java
  src/main/java/com/sparta/wuzuzu/domain/email/service/EmailAuthService.java
  src/main/java/com/sparta/wuzuzu/domain/user/controller/UserController.java
  src/main/java/com/sparta/wuzuzu/domain/user/dto/ReportUserRequest.java
  src/main/java/com/sparta/wuzuzu/domain/user/entity/User.java
  src/main/java/com/sparta/wuzuzu/domain/user/entity/UserRole.java
  src/main/java/com/sparta/wuzuzu/domain/user/service/UserService.java
  src/main/java/com/sparta/wuzuzu/global/config/WebSecurityConfig.java
Labels: bug, enhancement

#13 Feat/inyeong admin
  .gitignore
  src/main/java/com/sparta/wuzuzu/domain/admin/controller/AdminController.java
  src/main/java/com/sparta/wuzuzu/domain/admin/dto/AdminLoginRequest.java
  src/main/java/com/sparta/wuzuzu/domain/admin/dto/AdminVerifyRequest.java
  src/main/java/com/sparta/wuzuzu/domain/admin/dto/UserInformReadResponse.java
  src/main/java/com/sparta/wuzuzu/domain/admin/entity/Admin.java
  src/main/java/com/sparta/wuzuzu/domain/admin/repository/AdminRepository.java
  src/main/java/com/sparta/wuzuzu/domain/admin/service/AdminService.java
  src/main/java/com/sparta/wuzuzu/domain/email/controller/EmailAuthController.java
  src/main/java/com/sparta/wuzuzu/domain/email/service/EmailAuthService.java
  src/main/java/com/sparta/wuzuzu/domain/user/controller/AuthController.java
  src/main/java/com/sparta/wuzuzu/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/wuzuzu/domain/user/service/UserService.java
  src/main/java/com/sparta/wuzuzu/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/wuzuzu/global/jwt/JwtUtil.java
  src/main/java/com/sparta/wuzuzu/global/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/wuzuzu/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/wuzuzu/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/wuzuzu/global/security/UserDetailsServiceImpl.java
  src/main/resources/templates/index.html
Labels: bug, enhancement

#15 Fix/inyeong email auth
  src/main/java/com/sparta/wuzuzu/domain/email/controller/EmailAuthController.java
  src/main/java/com/sparta/wuzuzu/domain/email/dto/EmailAuthResponse.java
  src/main/java/com/sparta/wuzuzu/domain/email/service/EmailAuthService.java
  src/main/resources/templates/emailSend.html
Labels: bug, enhancement

#17 Feat/jjh-Redis 의 싱글 스레드 특성을 이용한 동시성 제어
  src/main/java/com/sparta/wuzuzu/domain/order/controller/OrderController.java
  src/main/java/com/sparta/wuzuzu/domain/order/service/OrderService.java
  src/main/java/com/sparta/wuzuzu/domain/sale_post/entity/SalePost.java
  src/main/java/com/sparta/wuzuzu/domain/sale_post/service/SalePostService.java
  src/main/java/com/sparta/wuzuzu/global/config/RedisConfig.java
Labels: enhancement

#18 Fix/inyeong auth
  src/main/java/com/sparta/wuzuzu/domain/user/entity/User.java
  src/main/java/com/sparta/wuzuzu/domain/user/service/UserService.java
  src/main/java/com/sparta/wuzuzu/global/jwt/JwtUtil.java
  src/main/java/com/sparta/wuzuzu/global/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/wuzuzu/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/wuzuzu/global/security/UserDetailsServiceImpl.java
Labels: enhancement

#21 Feat/chae react
  src/main/wuzuzu_fe/public/favicon.ico
  src/main/wuzuzu_fe/public/index.html
  src/main/wuzuzu_fe/public/logo192.png
  src/main/wuzuzu_fe/public/logo512.png
  src/main/wuzuzu_fe/src/logo.svg
Labels: enhancement

#29 Feat/chae react
  src/main/java/com/sparta/wuzuzu/domain/category/service/CategoryService.java
  src/main/wuzuzu_fe/src/App.js
  src/main/wuzuzu_fe/src/views/SignUp.js
Labels: enhancement
